
//desafio 01
//criação de array de objetos chamado "consertos", com 4 atributos: aparelho, itensconsertados, valores e pronto.

let consertos = [
    {
        aparelho:'liquidificador',
        itensConsertados:['motor','copo','tampa'],
        valores:[30,10,5],
        pronto:true
    },
    {
        aparelho:'purificador_de_agua',
        itensConsertados:['filtro','resistencia','conector'],
        valores:[12.50,20.30,11],
        pronto:false
    },  
    {
        aparelho:'aspirador_po',
        itensConsertados:['reservatorio','aste','tomada'],
        valores:[50,37,7],
        pronto:false
    },
    {
        aparelho:'enceradeira',
        itensConsertados:['pistão','bobina','engrenagem'],
        valores:[24,25,14],
        pronto:true
    },
    {
        aparelho:'bicicleta',
        itensConsertados:['filtrodeoleo','marcha','guidão'],
        valores:[44,55,66],
        pronto:true
    }  ,
    {
        aparelho:'skate',
        itensConsertados:['rodafrente','rodatras','parafusos'],
        valores:[22,22.5,5],
        pronto:true
    },
    {
        aparelho:'carrinho_remoto',
        itensConsertados:['controle','parachoque','teto'],
        valores:[34,15.6,22.3],
        pronto:false
    },
    {
        aparelho:'boneca',
        itensConsertados:['enchimento','olhos','alto_falante'],
        valores:[55.5,67.8,33.5],
        pronto:false
    },
    {
        aparelho:'mp3_player',
        itensConsertados:['botão_power','usb','visor'],
        valores:[4.21,5.30,30],
        pronto:true
    },
    {
        aparelho:'toca_disco',
        itensConsertados:['agulha','alto_falante','timer'],
        valores:[1.50,16.8,14.2],
        pronto:true
    },
    {
        aparelho:'secador',
        itensConsertados:['bobina','botao','resistencia'],
        valores:[3.40,6,9],
        pronto:true
    },
    {
        aparelho:'alexa',
        itensConsertados:['tela','alto_falante','timer'],
        valores:[97,88,99],
        pronto:false
    },
    {
        aparelho:'maquina_vintage',
        itensConsertados:['rolodefilme','flash','alça'],
        valores:[20.75,10,7],
        pronto:true
    },
    {
        aparelho:'mesa_digitalizadora',
        itensConsertados:['touch','caneta','bandeja'],
        valores:[40,30,10.50],
        pronto:false
    },
    {
        aparelho:'dvd_player',
        itensConsertados:['placadevideo','conectorHDMI','tomada'],
        valores:[77.3,50,6],
        pronto:true
    } 
];
module.exports = consertos;